dashboard:
    command: "tcp://0.0.0.0:80"
    environment:
        ORIGIN: "videoin-mzplus-com"
    external_links:
        - ambassador:localhost
    image: magvlab/video-transcode-admin:v_96
    labels:
        service: /srv/video-transcode-admin/main
        port: "80"
        proxycfg: "/proxy/video-transcode-admin/main"
    ports:
        - "80:80"
    restart: always
