wowza-streaming-engine:
    image: magvlab/wowza-streaming-engine:v1
    labels:
        service: /srv/wowza/live/engine
        port: "80"
    external_links:
        - agent
    ports:
        - "80:80"
        - "443:443"
        - "1935:1935"

wowza-streaming-agent:
    command: "--addr 0.0.0.0:20080 --advertise ${HostIP}"
    env_file: /etc/environ
    image: magvlab/wowza-streaming-agent:v_3
    ports:
        - "20080:20080"
    labels:
        service: /srv/wowza/live/agent
        port: "20080"
    external_links:
        - ambassador:localhost
        - agent
