wowza-streaming-engine:
    restart: always

wowza-streaming-agent:
    restart: always

logrotate:
    image: tutum/logrotate
    restart: always
    volumes:
        - /var/lib/docker/containers:/var/lib/docker/containers:rw
