wowza-streaming-engine:
    image: magvlab/wowza-streaming-engine:v1
    labels:
        service: /srv/wowza/live/engine
        port: "80"
    ports:
        - "80:80"
        - "443:443"
        - "1935:1935"

wowza-streaming-agent:
    command: "--addr 0.0.0.0:20080"
    image: magvlab/wowza-streaming-agent:v_9
    ports:
        - "20080:20080"
    labels:
        service: /srv/wowza/live/agent
        port: "20080"
    links:
        - wowza-streaming-engine
