agent:
    command: "--addr 0.0.0.0:20080"
    external_links:
        - "ambassador:localhost"
    image: magvlab/wowza-streaming-agent:v_15
    labels:
        service: /srv/wowza/live/agent
        port: "20080"
        proxy: '[{"name": "livestream", "net": "tcp", "src": ":6379", "srv": "/srv/redis/livestream"}]'
    ports:
        - "20080:20080"
    restart: always

engine:
    external_links:
        - "ambassador:localhost"
    image: magvlab/wowza-streaming-engine:v_4
    labels:
        service: /srv/wowza/live/engine
        port: "80"
        proxy: '[{"name": "livestream", "net": "tcp", "src": ":6379", "srv": "/srv/redis/livestream"}]'
    ports:
        - "80:80"
        - "443:443"
        - "1935:1935"
        - "8088:8088"
    restart: always
