ambassador:
    container_name: ambassador
    command:
        - "--addr"
        - "0.0.0.0:29091"
        - "--advertise"
        - "192.168.1.120:29091"
        - "--prefix"
        - "/debug/docker/ambassador/nodes"
        - "--proxy"
        - '{"name": "discovery", "net": "tcp", "src": ":2379", "dst": ["192.168.1.109:2379"]}'
        - "etcd://192.168.1.109:2379"
    env_file: /etc/environ
    environment:
        LOG_LEVEL: DEBUG
    image: jeffjen/ambd:v_40
    mem_limit: 128000000
    net: isolated_nw
    ports:
        - "29091:29091"

agent:
    container_name: agent
    command:
        - "--addr"
        - "0.0.0.0:29092"
        - "--advertise"
        - "192.168.1.120:2375"
        - "--prefix"
        - "/debug/docker/swarm/nodes"
        - "etcd://ambassador:2379"
    env_file: /etc/environ
    image: jeffjen/docker-monitor:v_39
    mem_limit: 128000000
    net: isolated_nw
    ports:
        - "29092:29092"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp:/tmp
