ambassador:
    env_file: /etc/environ
    image: jeffjen/docker-ambassador:v_3
    ports:
        - "127.0.0.1:29091:29091"

agent:
    command: "--addr 0.0.0.0:29092 --prefix /${cluster}/docker/swarm/nodes --advertise ${HostIP}:2375 etcd://discovery:2379"
    env_file: /etc/environ
    image: jeffjen/docker-monitor:v_18
    links:
        - ambassador:discovery
    ports:
        - "127.0.0.1:29092:29092"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
