ambassador:
    env_file: /etc/environ
    image: jeffjen/docker-ambassador:v_13
    ports:
        - "127.0.0.1:29091:29091"

agent:
    command:
        - "--addr"
        - "0.0.0.0:29092"
        - "--advertise"
        - "${HostIP}:2375"
        - "--prefix"
        - "/${cluster}/docker/swarm/nodes"
        - "etcd://discovery:2379"
    env_file: /etc/environ
    image: jeffjen/docker-monitor:v_28
    links:
        - ambassador:discovery
        - ambassador:localhost
    ports:
        - "127.0.0.1:29092:29092"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

logrotate:
    image: tutum/logrotate
    volumes:
        - /var/lib/docker/containers:/var/lib/docker/containers:rw
